# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Frigg < Formula
  desc ""
  homepage "https://github.com/PatrickLaabs/frigg"
  version "1.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/PatrickLaabs/frigg/releases/download/1.1.0/frigg_1.1.0_darwin_arm64.tar.gz"
      sha256 "142198ae1dcc301527bf3ca11fcf2c9bba56637641f4f95b7e8ef9a57d8d70a4"

      def install
        bin.install "frigg"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/PatrickLaabs/frigg/releases/download/1.1.0/frigg_1.1.0_darwin_amd64.tar.gz"
      sha256 "8d4bf26f878bf613a72098810514fe8ff955d1ad5ee1580545142be2b4491b1a"

      def install
        bin.install "frigg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/PatrickLaabs/frigg/releases/download/1.1.0/frigg_1.1.0_linux_arm64.tar.gz"
      sha256 "af089eed984280e927c34694455a4bca6488fc314f472cf2b29911e15027cf2b"

      def install
        bin.install "frigg"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/PatrickLaabs/frigg/releases/download/1.1.0/frigg_1.1.0_linux_amd64.tar.gz"
      sha256 "f4cb95d2e91a19dcd0a80b5479ad9a89f3ca1ab055d3d5a529d259520e4b5459"

      def install
        bin.install "frigg"
      end
    end
  end
end
