# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Frigg < Formula
  desc ""
  homepage "https://github.com/PatrickLaabs/frigg"
  version "1.1.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/PatrickLaabs/frigg/releases/download/1.1.2/frigg_1.1.2_darwin_arm64.tar.gz"
      sha256 "b49a22cda722b9e54c427b8edd9fad4f1f4aa1750d39cf97e28beb61299361f0"

      def install
        bin.install "frigg"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/PatrickLaabs/frigg/releases/download/1.1.2/frigg_1.1.2_darwin_amd64.tar.gz"
      sha256 "edb072f64218e2a1c80d1689c35bf9e9890a472154b6f2fd8c0ac90bb183f2a6"

      def install
        bin.install "frigg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/PatrickLaabs/frigg/releases/download/1.1.2/frigg_1.1.2_linux_arm64.tar.gz"
      sha256 "ee4e74aeb133170617b8c5f071c73f7fce4135fdc51b54bbf10ef6dea86637d5"

      def install
        bin.install "frigg"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/PatrickLaabs/frigg/releases/download/1.1.2/frigg_1.1.2_linux_amd64.tar.gz"
      sha256 "b08d5a4ab0b16378cb75cbac359e1e71e5ef3e199139c7c5fccc31fb30b946b8"

      def install
        bin.install "frigg"
      end
    end
  end
end
