package vars

// FriggVersion and VersionPreRelease constants are used to define the Version the Frigg CLI outputs on ./frigg version
const FriggVersion = "1.0.2"
const VersionPreRelease = ""
const GithubCliVersion = "2.45.0"
const KubectlVersion = "1.29.2"
const ClusterctlVersion = "1.6.1"
const K9sVersion = "0.32.3"

var RepoName = "argo-hub"
var FriggDirName = ".frigg"
var FriggTools = "tools"
var PrivatekeyName = "frigg-sshkeypair_gen"
var PublickeyName = "frigg-sshkeypair_gen.pub"
var PublickeyNameOnGh = "frigg-generated-publickey"
var BootstrapkubeconfigName = "bootstrapcluster.kubeconfig"
var ManagementKubeconfigName = "argohubmgmtcluster.kubeconfig"
var WorkloadKubeconfigName = "workloadcluster.kubeconfig"
var KindconfigName = "kind-config.yaml"
var ClusterctlConfigName = "clusterctl-config.yaml"
var CniName = "cni.yaml"
var VaultName = "mgmt-vault.yaml"
var ArgoCDWorkload = "argocd-workload-clusters.yaml"
var ArgoCDMgmt = "mgmt-argocd.yaml"
var ArgoCDAppsMgmt = "mgmt-argocd-apps.yaml"
var ArgoRolloutsMgmt = "mgmt-argocd-rollouts.yaml"
var ArgoEventsMgmt = "mgmt-argocd-events.yaml"
var ArgoWorkflowsMgmt = "mgmt-argocd-workflows.yaml"
var MgmtManifest = "argohubmgmtclusterManifest.yaml"
var WorkloadManifest = "workloadcluster.yaml"
var CurlMgmtManifest = "https://raw.githubusercontent.com/PatrickLaabs/frigg/main/templates/argohubmgmtclusterManifest.yaml"
var CurlWorkloadManifest = "https://raw.githubusercontent.com/PatrickLaabs/frigg/main/templates/workloadcluster.yaml"
