package vars

var RepoName = "friggs-mgmt-repo"
var FriggMgmtName = "friggmgmtcluster"
var FriggDirName = ".frigg"
var FriggTools = "tools"
var ControllerDir = "capi_controller"
var FriggMgmtGitOpsName = "friggs-mgmt-repo.git"
var FriggMgmtTemplateName = "--template=PatrickLaabs/friggs-mgmt-repo-template"
var PrivatekeyName = "frigg-sshkeypair_gen"
var PublickeyName = "frigg-sshkeypair_gen.pub"
var PublickeyNameOnGh = "frigg-generated-publickey"
var BootstrapkubeconfigName = "bootstrapcluster.kubeconfig"
var ManagementKubeconfigName = "friggmgmtcluster.kubeconfig"
var WorkloadKubeconfigName = "workloadcluster.kubeconfig"
var KindconfigName = "kind-config.yaml"
var ClusterctlConfigName = "clusterctl-config.yaml"
var CniName = "cni.yaml"
var VaultName = "mgmt-vault.yaml"
var ArgoCDWorkload = "argocd-workload-clusters.yaml"
var ArgoCDMgmt = "mgmt-argocd.yaml"
var ArgoCDAppsMgmt = "mgmt-argocd-apps.yaml"
var ArgoRolloutsMgmt = "mgmt-argocd-rollouts.yaml"
var ArgoEventsMgmt = "mgmt-argocd-events.yaml"
var ArgoWorkflowsMgmt = "mgmt-argocd-workflows.yaml"
var MgmtManifest = "friggmgmtclusterManifest.yaml"
var WorkloadManifest = "workloadcluster.yaml"
var VclusterWorkloadManifest = "vcluster-workloadcluster.yaml"
var CurlMgmtManifest = "https://raw.githubusercontent.com/PatrickLaabs/frigg/main/templates/friggmgmtclusterManifest.yaml"
var CurlWorkloadManifest = "https://raw.githubusercontent.com/PatrickLaabs/frigg/main/templates/workloadcluster.yaml"

// var CurlWorkloadVclusterManifest = "https://raw.githubusercontent.com/PatrickLaabs/frigg/main/templates/vcluster-workloadcluster.yaml"
var CurlWorkloadVclusterManifest = "https://raw.githubusercontent.com/PatrickLaabs/frigg/90-feat-introduce-vcluster-workload-cluster/templates/vcluster-workloadcluster.yaml"
var CertManagerManifest = "https://github.com/jetstack/cert-manager/releases/latest/download/cert-manager.yaml"
var CapiOperatorManifest = "https://github.com/kubernetes-sigs/cluster-api-operator/releases/latest/download/operator-components.yaml"
var CoreProviderName = "CapiCoreProv.yaml"
var ControlPlaneProvName = "CapiControlPlaneProv.yaml"
var BootstrapProvName = "CapiBootstrapProv.yaml"
var DockerInfraProvName = "DockerInfraProv.yaml"
var HelmAddonProvName = "AddonHelmProv.yaml"
